"""Added is_active fields

Revision ID: 345455b16eb8
Revises: 
Create Date: 2025-04-30 12:31:21.281211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345455b16eb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
